sudo: false
language: node_js
node_js:
- '10'
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/test-interface.git
  - secure: MCO49mwcjY0Rj5ExPCNKmBBxl1GANKVaVuL6dH8vLDOxrZhZ29A2MMS7x/95WY86zaEybOGqlilJWGOObSvWmE986d51agisk0l03UkNzjiqX84cz8zMZ3PP4mR7lLvR/8mg8ncMkKEM6JEfxChj6rL5CPIZSe19rVWY0hRtrX88/PBlc/6NsftSombJsRRHL/L6mwkJTJuGUbvf8Q0yUuwC+NmBS7BozhmTsObRgtIaJ0HXfMpI0GMD9Jo8frxtA7+Avipx1wQvBQyk0y7Aqgkg5Ih5vi0lEOSCX5n+V6/h6QljdoZfa3UjY+5M0K0hODfmZG/zhoeIU2skzf2pEManaqXUGdAj7DIwMpaOjni9Iywdt5sHl0iIZfOIHs4TT+5lUw9yDrHSX2QoP2tGaf1X/n09dSyhgzunDyUcxufCyV5w9vms4C/nLOSEJ++V03xuCWmcZGwjsk6AvSkAYSe+rKiQEHbPLk6ATDOhALoCsxEZtS5D9ZZW9yZS/NVV1zN8xkHsJ5gqBSOhdWMFf45+AoCxXUOMzhYb3toMbZAJvoicdqbIDqy95xDKThUwnJzagpPkdErDmZwkb2fz3H2jRBsSpBrndNrb/QzAXwUXllIFcPp0FEZkbeYXefPv+q//DdAFs570yFqdUZ3ATMgyg3QkrTIcJgJr9YT657Y=
