name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Render Documentation
        uses: openactive/extension-documentation-generator@master
        with:
          header: header.md
          context: test-interface.jsonld
          with_issues: false
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          enable_jekyll: true

      - name: Generate repo access token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.OA_AUTOMATION_APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.OA_AUTOMATION_APP_ID }}

      - name: Trigger tooling update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ steps.get_token.outputs.app_token }}
          repository: openactive/OpenActive.NET
          event-type: data-models-update
