name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Render Documentation
        uses: openactive/extension-documentation-generator@master
        with:
          header: header.md
          context: test-interface.jsonld
          with_issues: false
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          force_orphan: true
          enable_jekyll: true

      - name: Generate repo access token
        uses: tibdex/github-app-token@v1.1.1
        id: generate-token
        with:
          app_id: ${{ secrets.OA_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.OA_AUTOMATION_APP_PRIVATE_KEY }}

      - name: Trigger tooling update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: openactive/OpenActive.NET
          event-type: data-models-update
